#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/abtree
#
# IDENTIFICATION
#    src/backend/access/abtree/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/abtree
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	abtdedup.o \
	abtinsert.o \
	abtpage.o \
	abtree.o \
	abtsearch.o \
	abtsort.o \
	abtsplitloc.o \
	abtutils.o \
	abtvalidate.o \
	abtxlog.o \
	abtaggfuncs.o \
	abtversionstore.o

include $(top_srcdir)/src/backend/common.mk
